### ISSUE TITLE
Error when distilling CycleGan

### ISSUE THREAD

**Issue by jvillegassmule** [snap-research/CAT#15]
Hi again,
I am now trying to use CAT to train and distill a CycleGan transformation.
The training worked well but I am about to start distilling with:
```
 !python distill.py --dataroot /local_path/ \
  --dataset_mode unaligned \
  --distiller inception \
  --gan_mode lsgan \
  --log_dir /local_path/student \
  --restore_pretrained_G_path /local_path/teacher/checkpoints/best_A_net_G_A.pth \
  --restore_teacher_G_path /local_path/teacher/checkpoints/best_A_net_G_A.pth \
  --restore_D_path /local_path/teacher/checkpoints/best_A_net_D_A.pth \
  --real_stat_path /local_path/out_stat_B.npz\
  --nepochs 500 --nepochs_decay 500 \
  --save_latest_freq 25000 --save_epoch_freq 25 \
  --teacher_netG inception_9blocks --student_netG inception_9blocks \
  --pretrained_ngf 64 --teacher_ngf 64 --student_ngf 24 \
  --eval_batch_size 2 \
  --gpu_ids 0 \
  --norm batch \
  --norm_affine \
  --norm_affine_D \
  --norm_track_running_stats \
  --channels_reduction_factor 6 \
  --kernel_sizes 1 3 5 \
  --lambda_distill 1.0 \
  --prune_cin_lb 16 \
  --target_flops 6.6e9 \
  --distill_G_loss_type ka
```

But I keep getting a runtime Error( similar to the one fixed on Issue #11 -> https://github.com/snap-research/CAT/issues/11) 

```
Load network at /local_path/teacher/checkpoints/best_A_net_G_A.pth
Traceback (most recent call last):
  File "distill.py", line 13, in <module>
    trainer = Trainer('distill')
  File "/content/drive/MyDrive/CAT/trainer.py", line 80, in __init__
    model.setup(opt)
  File "/content/drive/MyDrive/CAT/distillers/base_inception_distiller.py", line 260, in setup
    self.load_networks(verbose)
  File "/content/drive/MyDrive/CAT/distillers/inception_distiller.py", line 192, in load_networks
    super(InceptionDistiller, self).load_networks(prune_continue)
  File "/content/drive/MyDrive/CAT/distillers/base_inception_distiller.py", line 362, in load_networks
    verbose)
  File "/content/drive/MyDrive/CAT/utils/util.py", line 139, in load_network
    net.load_state_dict(weights)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for InceptionGenerator:
	Missing key(s) in state_dict: "down_sampling.2.running_mean", "down_sampling.2.running_var",...
```
Lots of other missing keys.

Please let me know if there is something wrong or missing in my command line, (BTW the teacher training produced 4 Generator networks, which one should I use to distill the A to B generator? )

**Comment by deJQK** [comment]
Hi @jvillegassmule , thanks for your interest. Could you please also provide your script for running the teacher model? It seems that you are using `batch_norm` and track `running_stats` but in our original method we use instance norm without running stats for CycleGAN on Horse2Zebra. If you want to use norm layers with different type and property for the teacher and student, maybe during teacher loading you can set `strict` to `False` (which is `True` by default: [torch load_state_dict function](https://pytorch.org/docs/stable/generated/torch.nn.Module.html?highlight=load_state_dict#torch.nn.Module.load_state_dict)) in [util.py#L139](https://github.com/snap-research/CAT/blob/main/utils/util.py#L139), and comment this: [weight_transfer.py#L89](https://github.com/snap-research/CAT/blob/main/utils/weight_transfer.py#L89). Hope it helps!

**Comment by jvillegassmule** [comment]
Thank you for your answer, I am going to check your suggestions.  Here is my training command:

```
!python train.py --dataroot  /local_path/ \
  --model cycle_gan \
  --log_dir  /local_path/teacher \
  --netG inception_9blocks \
  --real_stat_A_path    /local_path/out_stat_A.npz  \
  --real_stat_B_path    /local_path/out_stat_B.npz \
  --nepochs 500 --nepochs_decay 500 \
  --gpu_ids 0 \
  --norm_affine \
  --norm_affine_D \
  --channels_reduction_factor 6 \
  --kernel_sizes 1 3 5
```


And I resumed it with:

```
 !python train.py --dataroot /local_path \
 --model cycle_gan \
 --log_dir   /local_path/teacher \
 --netG inception_9blocks \
 --real_stat_A_path  /local_path/out_stat_A.npz  \
 --real_stat_B_path  /local_path/out_stat_B.npz  \
 --nepochs  200\
 --nepochs_decay 400 \
 --gpu_ids 0 \
 --norm_affine \
 --norm_affine_D \
 --num_threads 32 \
 --channels_reduction_factor 6 \
 --kernel_sizes 1 3 5 \
 --epoch_base 300\
 --iter_base 50000\
 --save_latest_freq 10000 --save_epoch_freq 5 \
 --restore_G_A_path /local_path/teacher/checkpoints/latest_net_G_A.pth \
 --restore_D_A_path /local_pathteacher/checkpoints/latest_net_D_A.pth \
 --restore_G_B_path /local_path/teacher/checkpoints/latest_net_G_B.pth \
 --restore_D_B_path /local_path/teacher/checkpoints/latest_net_D_B.pth
```

**Comment by deJQK** [comment]
Hi @jvillegassmule , thanks for providing the scripts. Based on your scripts, just as I said before, you are using instance norm without tracking running stats for teacher model but batch norm with tracking for student model and there is discrepancy between the two.

**Comment by jvillegassmule** [comment]
thank you @deJQK, I took away the `norm_batch` and the `norm_track_running_stats` flags, but unfortunately now I am getting an error apparently when loading the discriminator:

```
Load network at /local_path/teacher/checkpoints/best_A_net_D_A.pth
Traceback (most recent call last):
  File "distill.py", line 13, in <module>
    trainer = Trainer('distill')
  File "/content/drive/MyDrive/CAT/trainer.py", line 80, in __init__
    model.setup(opt)
  File "/content/drive/MyDrive/CAT/distillers/base_inception_distiller.py", line 260, in setup
    self.load_networks(verbose)
  File "/content/drive/MyDrive/CAT/distillers/inception_distiller.py", line 192, in load_networks
    super(InceptionDistiller, self).load_networks(prune_continue)
  File "/content/drive/MyDrive/CAT/distillers/base_inception_distiller.py", line 364, in load_networks
    util.load_network(self.netD, self.opt.restore_D_path, verbose)
  File "/content/drive/MyDrive/CAT/utils/util.py", line 139, in load_network
    net.load_state_dict(weights)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for NLayerDiscriminator:
	size mismatch for model.0.weight: copying a param with shape torch.Size([64, 3, 4, 4]) from checkpoint, the shape in current model is torch.Size([128, 3, 4, 4]).
	size mismatch for model.0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for model.2.weight: copying a param with shape torch.Size([128, 64, 4, 4]) from checkpoint, the shape in current model is torch.Size([256, 128, 4, 4]).
	size mismatch for model.2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for model.3.weight: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for model.3.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for model.5.weight: copying a param with shape torch.Size([256, 128, 4, 4]) from checkpoint, the shape in current model is torch.Size([512, 256, 4, 4]).
	size mismatch for model.5.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for model.6.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for model.6.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512])....
```

lots of other size mismatches.

**Comment by deJQK** [comment]
Hi @jvillegassmule, thanks. You could try to follow the settings [here](https://github.com/snap-research/CAT/blob/main/scripts/cycle_gan/horse2zebra/train_inception_student_2p6B.sh).

**Comment by jvillegassmule** [comment]
Thank you @deJQK, seems to be working now,  the critical missing parameter was --ndf 64
