### ISSUE TITLE
get_real_stat.py  for custom dataset

### ISSUE THREAD

**Issue by Ashish-Abraham** [snap-research/CAT#20]
I am working on a pix2pix model and ran this code to get real_stats.npz file with the folder structure specified in `get_real_stat.py`
```
!python get_real_stat.py \
--dataroot database/sketch/trainA \
--dataset_mode single \
--output_path real_stat/sketch_stats_train_A.npz \
--direction BtoA \
--phase train
```

```
!python get_real_stat.py \
--dataroot database/sketch/trainB \
--dataset_mode single \
--output_path real_stat/sketch_stats_train_B.npz \
--direction BtoA \
--phase train
```
I am facing the error
`Traceback (most recent call last):
  File "get_real_stat.py", line 146, in <module>
    main(opt)
  File "get_real_stat.py", line 40, in main
    tensors = torch.cat(tensors, dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Got 256 and 560 in dimension 2 (The offending index is 909)`
<br>
Should I edit the dataloader for this or is it anything else ? Any help is appreciated, please.

**Comment by Ashish-Abraham** [comment]
The code actually worked on a subset of the data.
